### ISSUE TITLE
Allow descriptors represented in yaml

### ISSUE THREAD

**Issue by fjuniorr** [frictionlessdata/frictionless-r#66]
According to the specs all descriptors (eg. data package, table schema, etc) MUST be a JSON object. However, there are some [discussions](https://github.com/frictionlessdata/specs/issues/292) to support a YAML representation, and [frictionless-py already supports it](https://framework.frictionlessdata.io/docs/faq/#why-am-i-getting-the-error-cannot-extract-tabular-data-from-json).

This is a nice feature because it allows for a more readable and diffable documentation, especially for the `description` property in table schema which can make use of [YAML multiline strings](http://yaml-multiline.info/) for writing markdown without suffering the [pain of the JSON handling of newlines](https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json).

Compare

```yaml
fields:
- name: COD
  type: integer
  format: default
  description: |
    Código de dois dígitos que identificam o estado

    > Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  title: Código do Estado
- name: NOME
  type: string
  format: default
  title: Nome do Estado
- name: SIGLA
  type: string
  format: default
  title: Sigla do Estado
```

with

```json
{
  "fields": [
    {
      "name": "COD",
      "type": "integer",
      "format": "default",
      "description": "Código de dois dígitos que identificam o estado\n\n> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n",
      "title": "Código do Estado"
    },
    {
      "name": "NOME",
      "type": "string",
      "format": "default",
      "title": "Nome do Estado"
    },
    {
      "name": "SIGLA",
      "type": "string",
      "format": "default",
      "title": "Sigla do Estado"
    }
  ]
}
```

Because some [data packages are going to mix both JSON and YAML](https://github.com/dados-mg/datapackage-reprex/tree/yaml-schema), it would be nice to be able to write

```R
library("frictionless")

dp <- read_package("https://raw.githubusercontent.com/dados-mg/datapackage-reprex/yaml-schema/datapackage.json")
df <- dp |> read_resource("estados")
```

which currently fails with

```
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid string in json text.
                                       fields: - name: COD   type: int
                     (right here) ------^
```
